//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erp_V1.DAL.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMERCAMPAIGN
    {
        public int ID { get; set; }
        public int CustomerID { get; set; }
        public string CampaignName { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Impact { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
    }
}
