//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erp_V1.DAL.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerSegment
    {
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public string CustomerName { get; set; }
        public string CustomerEmail { get; set; }
        public string CustomerPhone { get; set; }
        public byte RecencyScore { get; set; }
        public byte FrequencyScore { get; set; }
        public byte MonetaryScore { get; set; }
        public int RecencyDays { get; set; }
        public int FrequencyCount { get; set; }
        public decimal MonetaryValue { get; set; }
        public short RfmScore { get; set; }
        public string Segment { get; set; }
        public string SegmentDescription { get; set; }
        public System.DateTime AnalysisDate { get; set; }
        public Nullable<System.DateTime> LastPurchaseDate { get; set; }
        public Nullable<System.DateTime> FirstPurchaseDate { get; set; }
        public decimal AverageOrderValue { get; set; }
        public int TotalOrders { get; set; }
    
        public virtual CUSTOMER CUSTOMER { get; set; }
    }
}
