//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erp_V1.DAL.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CUSTOMER()
        {
            this.CUSTOMERCONTRACT = new HashSet<CUSTOMERCONTRACT>();
            this.CUSTOMERCLASSIFICATION = new HashSet<CUSTOMERCLASSIFICATION>();
            this.CUSTOMERCAMPAIGN = new HashSet<CUSTOMERCAMPAIGN>();
            this.CUSTOMERDOCUMENT = new HashSet<CUSTOMERDOCUMENT>();
            this.CUSTOMERINTERACTION = new HashSet<CUSTOMERINTERACTION>();
            this.CUSTOMERPOINTS = new HashSet<CUSTOMERPOINTS>();
            this.CustomerSegment = new HashSet<CustomerSegment>();
            this.INVOICE = new HashSet<INVOICE>();
        }
    
        public int ID { get; set; }
        public string Cust_Address { get; set; }
        public string Cust_Phone { get; set; }
        public string Notes { get; set; }
        public string CustomerName { get; set; }
        public bool isDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<long> baky { get; set; }
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUSTOMERCONTRACT> CUSTOMERCONTRACT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUSTOMERCLASSIFICATION> CUSTOMERCLASSIFICATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUSTOMERCAMPAIGN> CUSTOMERCAMPAIGN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUSTOMERDOCUMENT> CUSTOMERDOCUMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUSTOMERINTERACTION> CUSTOMERINTERACTION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CUSTOMERPOINTS> CUSTOMERPOINTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerSegment> CustomerSegment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INVOICE> INVOICE { get; set; }
    }
}
