//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erp_V1.DAL.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DELIVERY
    {
        public int ID { get; set; }
        public int SalesID { get; set; }
        public Nullable<int> DeliveryPersonID { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> AssignedDate { get; set; }
        public Nullable<System.DateTime> DeliveredDate { get; set; }
        public bool isDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual SALES SALES { get; set; }
    }
}
