//------------------------------------------------------------------------------ 
// <auto-generated> 
//     This code was generated from a template. 
// 
//     Manual changes to this file may cause unexpected behavior in your application. 
//     Manual changes to this file will be overwritten if the code is regenerated. 
// </auto-generated> 
//------------------------------------------------------------------------------ 
 
namespace Erp_V1.DAL.DAL 
{ 
    using System; 
    using System.Collections.Generic; 
 
    public partial class INVOICE_ITEM 
    { 
        public int ID { get; set; } 
        public int InvoiceID { get; set; } 
        public int ProductID { get; set; } 
        public int CategoryID { get; set; } 
        public string ProductName { get; set; } 
        public string Description { get; set; } 
        public int Quantity { get; set; } 
        public decimal UnitPrice { get; set; } 
        public decimal DiscountPercentage { get; set; } 
        public decimal DiscountAmount { get; set; } 
        public decimal LineTotal { get; set; } 
        public System.DateTime CreatedDate { get; set; } 
        public Nullable<System.DateTime> ModifiedDate { get; set; } 
        public string CreatedBy { get; set; } 
        public string ModifiedBy { get; set; } 
        public bool isDeleted { get; set; } 
        public Nullable<System.DateTime> DeletedDate { get; set; } 
 
        public virtual INVOICE INVOICE { get; set; } 
        public virtual PRODUCT PRODUCT { get; set; } 
    } 
}
