//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erp_V1.DAL.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOGIN_HISTORY
    {
        public int Id { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public string AttemptedUserNo { get; set; }
        public System.DateTime Timestamp { get; set; }
        public bool WasSuccessful { get; set; }
        public string IpAddress { get; set; }
        public string UserAgent { get; set; }
        public string Location { get; set; }
    }
}
