//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erp_V1.DAL.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class erp_v2Entities : DbContext
    {
        public erp_v2Entities()
            : base("name=erp_v2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CATEGORY> CATEGORY { get; set; }
        public virtual DbSet<CUSTOMER> CUSTOMER { get; set; }
        public virtual DbSet<PRODUCT> PRODUCT { get; set; }
        public virtual DbSet<SALES> SALES { get; set; }
        public virtual DbSet<SUPPLIER> SUPPLIER { get; set; }
        public virtual DbSet<PURCHASES> PURCHASES { get; set; }
        public virtual DbSet<PRODUCT_RETURN> PRODUCT_RETURN { get; set; }
        public virtual DbSet<PROFIT> PROFIT { get; set; }
        public virtual DbSet<DEPARTMENT> DEPARTMENT { get; set; }
        public virtual DbSet<EMPLOYEE> EMPLOYEE { get; set; }
        public virtual DbSet<POSITION> POSITION { get; set; }
        public virtual DbSet<ROLE> ROLE { get; set; }
        public virtual DbSet<PERMISSION> PERMISSION { get; set; }
        public virtual DbSet<PERMISSIONSTATE> PERMISSIONSTATE { get; set; }
        public virtual DbSet<MONTH> MONTH { get; set; }
        public virtual DbSet<SALARY> SALARY { get; set; }
        public virtual DbSet<TASK> TASK { get; set; }
        public virtual DbSet<TASKSTATE> TASKSTATE { get; set; }
        public virtual DbSet<ROLEPERMISSION> ROLEPERMISSION { get; set; }
        public virtual DbSet<CUSTOMERCAMPAIGN> CUSTOMERCAMPAIGN { get; set; }
        public virtual DbSet<CUSTOMERCLASSIFICATION> CUSTOMERCLASSIFICATION { get; set; }
        public virtual DbSet<CUSTOMERCONTRACT> CUSTOMERCONTRACT { get; set; }
        public virtual DbSet<CUSTOMERDOCUMENT> CUSTOMERDOCUMENT { get; set; }
        public virtual DbSet<CUSTOMERINTERACTION> CUSTOMERINTERACTION { get; set; }
        public virtual DbSet<CUSTOMERPOINTS> CUSTOMERPOINTS { get; set; }
        public virtual DbSet<SupplierCommunication> SupplierCommunication { get; set; }
        public virtual DbSet<SupplierContract> SupplierContract { get; set; }
        public virtual DbSet<SupplierPerformance> SupplierPerformance { get; set; }
        public virtual DbSet<SupplierQuote> SupplierQuote { get; set; }
        public virtual DbSet<SupplySchedule> SupplySchedule { get; set; }
        public virtual DbSet<EXPENSE_CATEGORIES> EXPENSE_CATEGORIES { get; set; }
        public virtual DbSet<EXPENSES> EXPENSES { get; set; }
        public virtual DbSet<DELIVERY> DELIVERY { get; set; }
        public virtual DbSet<CustomerSegment> CustomerSegment { get; set; }
        public virtual DbSet<INVOICE> INVOICE { get; set; }
        public virtual DbSet<LOGIN_HISTORY> LOGIN_HISTORY { get; set; }
        public virtual DbSet<Notifications> Notifications { get; set; }
        public virtual DbSet<PartialPayments> PartialPayments { get; set; }
    }
}
