//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erp_V1.DAL.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationSettings
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public string NotificationType { get; set; }
        public bool IsEnabled { get; set; }
        public string ThresholdValue { get; set; }
        public string AdditionalSettings { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
    }
}