//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erp_V1.DAL.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notifications
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Message { get; set; }
        public string Type { get; set; }
        public System.DateTime Timestamp { get; set; }
        public bool IsRead { get; set; }
        public string TargetUrl { get; set; }
        public string RelatedEntityType { get; set; }
        public Nullable<int> RelatedEntityId { get; set; }
        public string Severity { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> EmployeeId { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
    }
}
