//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erp_V1.DAL.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERMISSION
    {
        public int ID { get; set; }
        public int EmployeeID { get; set; }
        public int PermissionState { get; set; }
        public System.DateTime PermissionStartDate { get; set; }
        public System.DateTime PermissionEndDate { get; set; }
        public int PermissionDay { get; set; }
        public string PermissionExplanation { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual PERMISSIONSTATE PERMISSIONSTATE1 { get; set; }
    }
}
