//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erp_V1.DAL.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALARY
    {
        public int ID { get; set; }
        public int EmployeeID { get; set; }
        public int MonthID { get; set; }
        public int Year { get; set; }
        public int Amount { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual MONTH MONTH { get; set; }
    }
}
