//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erp_V1.DAL.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SALES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SALES()
        {
            this.DELIVERY = new HashSet<DELIVERY>();
            this.PartialPayments = new HashSet<PartialPayments>();
        }
    
        public int ID { get; set; }
        public int ProductID { get; set; }
        public int CustomerID { get; set; }
        public int CategoryID { get; set; }
        public int ProductSalesAmout { get; set; }
        public int ProductSalesPrice { get; set; }
        public Nullable<long> Total { get; set; }
        public Nullable<long> TotalOrder { get; set; }
        public Nullable<long> Madfou3 { get; set; }
        public Nullable<long> Baky { get; set; }
        public System.DateTime SalesDate { get; set; }
        public bool isDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<float> MaxDiscount { get; set; }
        public string TransactionId { get; set; }
        public int PaymentState { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DELIVERY> DELIVERY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PartialPayments> PartialPayments { get; set; }
    }
}
