//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erp_V1.DAL.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierCommunication
    {
        public int CommunicationID { get; set; }
        public int SupplierID { get; set; }
        public System.DateTime CommunicationDate { get; set; }
        public string Type { get; set; }
        public string Subject { get; set; }
        public string Content { get; set; }
        public string ReferenceLink { get; set; }
    
        public virtual SUPPLIER SUPPLIER { get; set; }
    }
}
