//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erp_V1.DAL.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierQuote
    {
        public int QuoteID { get; set; }
        public System.Guid RequestID { get; set; }
        public int SupplierID { get; set; }
        public System.DateTime QuoteDate { get; set; }
        public decimal TotalAmount { get; set; }
        public string Currency { get; set; }
        public string Details { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual SUPPLIER SUPPLIER { get; set; }
    }
}
