//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Erp_V1.DAL.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TASK
    {
        public int ID { get; set; }
        public string TaskTitle { get; set; }
        public string TaskContent { get; set; }
        public System.DateTime TaskStartDate { get; set; }
        public Nullable<System.DateTime> TaskDeliveryDate { get; set; }
        public int TaskState { get; set; }
        public int EmployeeID { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
        public virtual TASKSTATE TASKSTATE1 { get; set; }
    }
}
